version: 2

sphinx:
  builder: html
  configuration: python/docs/source/conf.py

submodules:
  include: all
  recursive: true

conda:
  environment: environment.yml

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  jobs:
    post_install:
      - bash ./install
