version: 2

sphinx:
  builder: html
  configuration: python/docs/source/conf.py

conda:
  environment: environment.yml

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.10"
  jobs:
    post_install:
      - conda activate pygetm ; bash ./install
