version: 2

sphinx:
  builder: html
  configuration: python/docs/source/conf.py

submodules:
  include: all
  recursive: true

conda:
  environment: environment-readthedocs.yml

build:
  os: ubuntu-lts-latest
  tools:
    python: miniconda-latest
  jobs:
    post_install:
      - bash ./install
      - pip install ford
