version: 2

sphinx:
  builder: html
  configuration: python/docs/source/conf.py

submodules:
  include: all
  recursive: true

conda:
  environment: environment-readthedocs.yml

build:
  os: "ubuntu-20.04"
  tools:
    python: "miniconda3-4.7"
  jobs:
    post_install:
      - bash ./install
      - pip install ford
