name: pygetm
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - cython
  - xarray
  - jupyterlab
  - cmake
  - numpy
  - matplotlib
  - scipy
  - ipympl
  - netcdf4
  - pyyaml
  - dask
  - cartopy
  - proj
  - pip:
    - mpi4py