package:
  name: pygetm
  version: "0.7"

source:
  git_url: https://github.com/BoldingBruggeman/getm-rewrite.git

build:
  entry_points:
    - pygetm-subdiv = pygetm.subdiv:main
    - pygetm-test-scaling = pygetm.parallel:test_scaling_command
    - pygetm-compare-nc = pygetm.util.compare_nc:compare_command

requirements:
  host:
    - python
    - numpy
    - pip
    - setuptools
  build:
    - cython
    - cmake
    - make                       # [not win]
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}  # [not win]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - xarray
    - mpi4py
    - netCDF4
    - pyyaml # for FABM

test:
  requires:
    - scipy
    - git
  imports:
    - pygetm
  commands:
    - pygetm-subdiv -h
    - pygetm-test-scaling -h
    - pygetm-compare-nc -h
    - set GETM_SETUPS_DIR=./getm-setups # [win]
    - export GETM_SETUPS_DIR=./getm-setups # [unix]
    - git clone https://git.code.sf.net/p/getm/getm-setups
    - python -m unittest discover -s python/tests -v
  source_files:
    - python/tests/*.py
    - python/examples/north_sea.py

about:
  home: https://pygetm.readthedocs.io
  license: GPL
