package:
  name: pygetm
  version: {{ environ.get("GIT_DESCRIBE_TAG", "").lstrip("v") }}

source:
  - git_url: https://github.com/BoldingBruggeman/getm-rewrite.git
  - git_url: https://git.code.sf.net/p/getm/getm-setups
    git_depth: 1
    folder: getm-setups

build:
  entry_points:
    - pygetm-subdiv = pygetm.subdiv:main
    - pygetm-test-scaling = pygetm.parallel:test_scaling_command
    - pygetm-compare-nc = pygetm.util.compare_nc:compare_command

requirements:
  host:
    - python
    - numpy
    - pip
    - setuptools
  build:
    - cython
    - cmake
    - make                       # [not win]
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}  # [not win]
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - xarray
    - mpi4py
    - netCDF4
    - pyfabm>=2

test:
  requires:
    - scipy
  imports:
    - pygetm
  commands:
    - pygetm-subdiv -h
    - pygetm-test-scaling -h
    - pygetm-compare-nc -h
    - set GETM_SETUPS_DIR=./getm-setups # [win]
    - export GETM_SETUPS_DIR=./getm-setups # [unix]
    - python -m unittest discover -s python/tests -v
  source_files:
    - python/tests/*.py
    - python/examples/north_sea.py
    - getm-setups/NorthSea

about:
  home: https://pygetm.readthedocs.io
  summary: Python-based 3D hydrodynamic model for coastal oceans
  description: |
    pygetm is a rewrite of the General Estuarine Transport Model (GETM)
    in Python (mostly) and Fortran (performance-critical sections)
  license: GPL
  doc_url: https://pygetm.readthedocs.io
  dev_url: https://github.com/BoldingBruggeman/getm-rewrite
